Vagrant.configure("2") do |config|

  # Vars
  pn = "private_network"

  vms = [
    { name: "vm1" },
    { name: "vm2" }
  ]

  config.vm.define "dhcp_server" do |dhcp|
    dhcp.vm.box = "hashicorp/bionic64"
    dhcp.vm.hostname = "dhcp-server"
    dhcp.vm.network pn, type: "dhcp"
    dhcp.vm.provision "shell", path: ".provision/scripts/dhcp.sh"
  end

  vms.each_with_index do |vm, index|
    config.vm.define vm[:name] do |machine|
      machine.vm.box = "ubuntu/jammy64"
      machine.vm.hostname = vm[:name]
      machine.vm.network pn, type: "dhcp"
    end
  end
end