version: '3'

services:
  web:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ../../testfiles/nginx.conf:/etc/nginx/nginx.conf:ro
      - ../../testfiles/index.html:/usr/share/nginx/html/index.html
    environment:
      - SERVER_NAME=Marc
    networks:
      - my-network

  data-service:
    image: alpine:latest
    volumes:
      - .:/app
    networks:
      - my-network

networks:
  my-network:
    driver: bridge