Vagrant.configure("2") do |config|

  # Vars
  base_ip = "192.168.56."
  start_ip = 10
  pn = "private_network"

  vms = [
    { name: "vm1" },
    { name: "vm2" }
  ]

  vms.each_with_index do |vm, index|
    config.vm.define vm[:name] do |machine|
      machine.vm.box = "ubuntu/jammy64"
      machine.vm.hostname = vm[:name]
      machine.vm.network pn, ip: "#{base_ip}#{start_ip + index}"
    end
  end
end