- name: Running system updates, htop installation and setting hostname.
  become: true
  hosts: all
  vars_files:
    - ../secrets.yaml
  tasks:
    - name: Running system updates
    # If not working change it to "ansible.builtin.dnf"
      ansible.builtin.package:
        name: "*"
        state: latest

    - name: Installing htop
      ansible.builtin.package:
        name: htop
        state: present
        
    - name: Setting a hostname
      ansible.builtin.hostname:
        name: "{{ inventory_hostname }}"
        use: systemd
