# - hosts: all
#   become: yes
#   roles:
#     - common

# - hosts: webserver
#   become: yes
#   roles:
#     - webserver

- hosts: dbserver
  become: yes
  tasks:
    - name: Install pip and required MySQL packages
      become: true
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - mysql-server
        - python-pip
        - python-dev
        - libmysqlclient-dev

    - name: Install MySQL-python using pip
      become: true
      pip:
        name: MySQL-python==1.2.3
      tags: ['mysql-python']



- hosts: dbserver
  vars:
      mysql_password: "root"
      mysql_user: "root"
  roles:
    - role: mysql
      become: yes