---
- name: Ensure MySQL databases are present.
  become: true
  mysql_db:
    name: "{{ item.name }}"
    collation: "{{ item.collation }}"
    encoding: "{{ item.encoding }}"
    state: present
  loop:
    - { name: 'vagrant_db', collation: 'latin1_general_ci', encoding: 'latin1' }
