---
- name: Ensure MySQL users are present.
  mysql_user:
    name: "{{ item.name }}"
    host: "{{ item.host | default('localhost') }}"
    password: "{{ item.password }}"
    priv: "{{ item.priv | default('*.*:USAGE') }}"
    state: "{{ item.state | default('present') }}"
    append_privs: "{{ item.append_privs | default('no') }}"
    encrypted: "{{ item.encrypted | default('no') }}"
    login_host: "{{ mysql_host | default('localhost') }}"
    login_user: "{{ mysql_user }}"
    login_password: "{{ mysql_password }}"
  with_items: "{{ mysql_users }}"
  #no_log: "{{ mysql_hide_passwords }}"
