version: '3'

services:
  web:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ../../testfiles/nginx.conf:/etc/nginx/nginx.conf:ro
      - ../../testfiles/index.html:/usr/share/nginx/html/index.html
    environment:
      - SERVER_NAME=Marc

  data-service:
    image: alpine:latest
    volumes:
      - .:/app