# docker-compose.yml
version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 9090:80
    environment:
      - DEBUG=true
    volumes:
      - ./index.html:/app/index.html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    restart: always
