services:
  uploader:
    build: ./uploader
    ports:
      - "5001:5001"
    volumes:
      - shared_files:/app/files
  
  downloader:
    build: ./downloader
    ports: 
      - "5000:5000"
    volumes:
      - shared_files:/app/files

volumes:
  shared_files:
    driver: local

